# configuration for "master" branch
-
  branches:
    only:
      - master
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  environment:
    apiKey:
      secure: 2ZZXSRRBupkaRGRnD1zefkkjmURoXN+QzdeutbdwckTXmmPpe7jmr6HQpgm0R2C4
  before_build:
    - ps: gitversion /l console /output buildserver
    - nuget setapikey %apiKey% -Verbosity quiet
  build_script:
    - build.bat Caliburn.Micro.TestingHelpers\Caliburn.Micro.TestingHelpers.csproj /t:Deploy /v:m
#  after_build:
#    - ps: >-
#      $wc = New-Object 'System.Net.WebClient'
#    
#      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\Caliburn.Micro.TestingHelpers.Tests.xml))

# all other branches
-
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  before_build:
    - ps: gitversion /l console /output buildserver
  build_script:
    - build.bat Caliburn.Micro.TestingHelpers\Caliburn.Micro.TestingHelpers.csproj /t:Deploy /v:m
 # after_build:
 # - ps: >-
 #     $wc = New-Object 'System.Net.WebClient'
 #   
 #     $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\Caliburn.Micro.TestingHelpers.Tests.xml))
